name: Run on Close PR
on:
  workflow_dispatch:
    inputs:
      none:
        description: "Deploy Syft Documentation"
        required: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run arbitrary shell command
          run: |
            echo "Running on ${{ github.event_name }}"
            echo "Running on ${{ github.event.inputs.none }}"
    